### ISSUE TITLE
Cost of kits

### ISSUE THREAD

**Issue by whaleygeek** [explorestem/rpi_kit#1]
The PartsList.pdf does not yet contain costings. As a rough guide, we had 33 kits so got some bulk discounts. Each kit cost around £149 to fund, for 33 kits. 

The foam inserts were made with a custom tooling, this tooling cost has now been met, so if others wanted identical foam inserts they could use our tooling to avoid that cost. However, there is a minimum order qty on the foam of 100 at a time (so you'd need to clump together with others to get a good per-part price). Cases were printed with a custom single colour silk screen print.

Core items were bought from gratnells, rapid electronics, 4tronix, pimoroni, maplin. Some suppliers provided slight bulk discounts.

**Comment by explorestem** [comment]
I’m not sure who this went to but the prices I believe are way over that. Will send you the updated figures later this week.
